/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <ffmpeg.h>
/* Header for class com_lzx_jni_Do */

#ifndef _Included_com_lzx_jni_Do
#define _Included_com_lzx_jni_Do
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzx_jni_Do
 * Method:    getstringfromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzx_jni_Do_getstringfromC
        (JNIEnv *, jobject, jint, jobjectArray);
JNIEXPORT jint JNICALL Java_com_lzx_jni_Do_decode
        (JNIEnv *, jobject, jstring, jstring);
JNIEXPORT jint JNICALL Java_com_lzx_jni_Do_intream
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
